# Generated by Django 4.2.13 on 2024-07-17 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=255)),
                ('store_email', models.EmailField(max_length=254)),
                ('address', models.TextField(max_length=255)),
                ('bio', models.TextField(blank=True, null=True)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=255)),
                ('shop_address', models.CharField(blank=True, max_length=255, null=True)),
                ('shop_city', models.CharField(blank=True, max_length=255, null=True)),
                ('shop_state', models.CharField(blank=True, max_length=255, null=True)),
                ('shop_postal_code', models.CharField(blank=True, max_length=50, null=True)),
                ('shop_country', models.CharField(blank=True, max_length=255, null=True)),
                ('shop_type', models.CharField(blank=True, choices=[('INDIVIDUAL', 'Individual'), ('TRADER_BUSINESS', 'Trader Business')], max_length=50, null=True)),
                ('art_specialization', models.CharField(blank=True, choices=[('PAINTING', 'Painting'), ('JEWELLERY', 'Jewellery'), ('POTTERY', 'Pottery'), ('DECORATION', 'Decoration'), ('OTHER', 'Other')], max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('upload_date_time', models.DateTimeField(auto_now_add=True)),
                ('ar_model_ref', models.URLField(blank=True, null=True)),
                ('availability', models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], max_length=50)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.details')),
            ],
        ),
    ]
