# Generated by Django 4.2.13 on 2024-07-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ar_model_ref',
            field=models.FileField(default='hehe', upload_to=''),
            preserve_default=False,
        ),
    ]
