# Generated by Django 4.2.13 on 2024-07-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0003_alter_product_ar_model_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ar_model_ref',
            field=models.FileField(default='asdfa', upload_to=''),
            preserve_default=False,
        ),
    ]
