# Generated by Django 4.2.13 on 2024-07-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0004_alter_product_ar_model_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('PAINTING', 'Painting'), ('JEWELLERY', 'Jewellery'), ('POTTERY', 'Pottery'), ('DECORATION', 'Decoration')], default='PAINTING', max_length=255),
        ),
    ]
