# Generated by Django 4.2.13 on 2024-07-21 10:23

import artist.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0005_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ar_model_image',
            field=models.ImageField(default='Hehe', upload_to='ar_model_images/', validators=[artist.models.validate_image_file_type]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='ar_model_ref',
            field=models.FileField(upload_to='ar_models/', validators=[artist.models.validate_file_type]),
        ),
    ]
